import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, stat, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import Fastify from 'fastify';
import multipart from '@fastify/multipart';
import WebTorrent from 'webtorrent';
import { TorrentEngine } from '../src/torrent/engine.js';
import { MediaService } from '../src/stream/remuxer.js';
import { torrentRoutes } from '../src/routes/torrentRoutes.js';
import { config } from '../src/config/env.js';
import { downloadDirectory } from '../src/torrent/downloadStorage.js';

const offline = { dht: false as const, tracker: false as const, lsd: false, natUpnp: false as const, natPmp: false, utp: false };
test('cold magnet via HTTP discovers metadata and streams MKV before full download; binary upload deduplicates', { timeout: 120000 }, async t => {
  const folder = await mkdtemp(join(tmpdir(), 'lumora-cold-'));
  const seeder = new WebTorrent({ ...offline, uploadLimit: 1500000 });
  const engine = new TorrentEngine(offline); const media = new MediaService(engine); const app = Fastify();
  t.after(async () => {
    await media.close(); app.server.closeAllConnections(); await app.close();
    for (const hash of engine.sessions.keys()) await engine.remove(hash);
    await engine.destroy(); await new Promise<void>(resolve => seeder.destroy(() => resolve()));
    await rm(folder, { recursive: true, force: true });
  });
  const file = join(folder, 'cold-start.mkv');
  await promisify(execFile)(config.FFMPEG_PATH, ['-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=640x360:rate=24', '-f', 'lavfi', '-i', 'sine=sample_rate=48000', '-t', '60', '-c:v', 'libx264', '-preset', 'ultrafast', '-g', '24', '-pix_fmt', 'yuv420p', '-b:v', '6M', '-minrate', '6M', '-maxrate', '6M', '-bufsize', '6M', '-x264-params', 'nal-hrd=cbr:force-cfr=1', '-c:a', 'aac', file]);
  assert.ok((await stat(file)).size > 32 * 1024 ** 2);
  const seed = seeder.seed(file, { announce: [] }); await once(seed, 'seed');
  await app.register(multipart); await torrentRoutes(app, engine, media); await media.listen(); await app.listen({ host: '127.0.0.1', port: 0 });
  const address = app.server.address(); assert.ok(address && typeof address !== 'string');
  const origin = `http://127.0.0.1:${address.port}`;
  const added = await fetch(`${origin}/api/magnet`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ magnet: `magnet:?xt=urn:btih:${seed.infoHash}` }) });
  assert.equal(added.status, 202); const hash = (await added.json() as { infoHash: string }).infoHash;
  const session = engine.get(hash); const peer = seeder.address(); assert.ok(peer && typeof peer !== 'string');
  session.torrent.addPeer(`127.0.0.1:${peer.port}`);
  if (!session.file) await once(session.torrent, 'ready');
  assert.equal(session.selector!.initialBufferReady, false);
  const selections = (session.torrent as any)._selections._items as { to: number }[];
  assert.ok(selections.every(entry => entry.to < 2 * 1024 ** 2 / session.torrent.pieceLength + 1), 'cold startup selects only header pieces');
  const started = Date.now(); const controller = new AbortController();
  const response = await fetch(`${origin}/api/stream/${hash}`, { signal: controller.signal });
  assert.equal(response.status, 200); const reader = response.body!.getReader(); const first = await reader.read();
  assert.ok(first.value?.length); assert.ok(session.file!.progress < 1, 'playback must start before the whole MKV is downloaded');
  assert.equal(media.metrics.probes, 1, 'background preparation and stream requests share one inspection');
  assert.ok(session.initialReadyAt, 'header readiness is recorded separately from media preparation');
  t.diagnostic(`First remux bytes after ${Date.now() - started}ms, ${(session.file!.progress * 100).toFixed(1)}% downloaded, source ${(session.file!.length / 1024 ** 2).toFixed(1)} MiB`);
  controller.abort(); await reader.cancel().catch(() => undefined);
  const body = new FormData(); body.append('file', new Blob([new Uint8Array(seed.torrentFile)]), 'sample.torrent');
  const upload = await fetch(`${origin}/api/upload`, { method: 'POST', body });
  assert.equal(upload.status, 202); assert.equal((await upload.json() as { infoHash: string }).infoHash, hash); assert.equal(engine.sessions.size, 1);
  const refreshed = await fetch(`${origin}/api/torrents/${hash}/refresh`, { method: 'POST' }); assert.equal(refreshed.status, 200);
  const download = downloadDirectory(config.DATA_DIR, session.torrent.name, hash)!;
  const removed = await fetch(`${origin}/api/torrents/${hash}`, { method: 'DELETE' });
  assert.equal(removed.status, 200); assert.deepEqual(await removed.json(), { removed: true, dataDeleted: true });
  await assert.rejects(stat(download), { code: 'ENOENT' });
  assert.equal(engine.sessions.size, 0);
});
